2022-01-02 12:04:12,488 DEBUG com.pravinkatiyar.onlinetest.utils.APIFilter [restartedMain] Filter 'aPIFilter' configured for use
2022-01-02 12:04:14,393 INFO com.pravinkatiyar.onlinetest.OnlinetestApplication [restartedMain] Started OnlinetestApplication in 3.198 seconds (JVM running for 1077.624)
2022-01-02 12:04:17,890 INFO org.springframework.web.servlet.DispatcherServlet [http-nio-8110-exec-1] Initializing Servlet 'dispatcherServlet'
2022-01-02 12:04:17,893 INFO org.springframework.web.servlet.DispatcherServlet [http-nio-8110-exec-1] Completed initialization in 2 ms
2022-01-02 12:04:17,921 DEBUG com.pravinkatiyar.onlinetest.aop.LoggingAspect [http-nio-8110-exec-1] Enter: com.pravinkatiyar.onlinetest.controller.UserController.createUser() with argument[s] = [User [id=, username=g4ffh2gf, password=vgvg, firstName=vh, lastName=vhv, gender=, email=gfh@gmail.com, phone=9874563210, enabled=true]]
2022-01-02 12:04:17,929 DEBUG com.pravinkatiyar.onlinetest.aop.LoggingAspect [http-nio-8110-exec-1] Enter: com.pravinkatiyar.onlinetest.service.impl.UserServiceImpl.createUser() with argument[s] = [User [id=, username=g4ffh2gf, password=vgvg, firstName=vh, lastName=vhv, gender=, email=gfh@gmail.com, phone=9874563210, enabled=true], [com.pravinkatiyar.onlinetest.entity.UserRole@27b7b17a]]
2022-01-02 12:04:17,979 ERROR com.pravinkatiyar.onlinetest.aop.LoggingAspect [http-nio-8110-exec-1] Exception in com.pravinkatiyar.onlinetest.service.impl.UserServiceImpl.createUser() with cause = NULL
2022-01-02 12:04:17,980 ERROR com.pravinkatiyar.onlinetest.aop.LoggingAspect [http-nio-8110-exec-1] Exception in com.pravinkatiyar.onlinetest.controller.UserController.createUser() with cause = NULL
2022-01-02 12:04:17,988 WARN org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver [http-nio-8110-exec-1] Resolved [com.pravinkatiyar.onlinetest.exception.UserAlreadyExistsException: User with username: g4ffh2gf already exists in database!]
2022-01-02 12:06:03,630 DEBUG com.pravinkatiyar.onlinetest.aop.LoggingAspect [http-nio-8110-exec-3] Enter: com.pravinkatiyar.onlinetest.controller.UserController.createUser() with argument[s] = [User [id=, username=g4ffh2gf, password=vghv, firstName=chg, lastName=vjg, gender=, email=gcvg@gmail.com, phone=9874563210, enabled=true]]
2022-01-02 12:06:03,631 DEBUG com.pravinkatiyar.onlinetest.aop.LoggingAspect [http-nio-8110-exec-3] Enter: com.pravinkatiyar.onlinetest.service.impl.UserServiceImpl.createUser() with argument[s] = [User [id=, username=g4ffh2gf, password=vghv, firstName=chg, lastName=vjg, gender=, email=gcvg@gmail.com, phone=9874563210, enabled=true], [com.pravinkatiyar.onlinetest.entity.UserRole@7ce6cbb8]]
2022-01-02 12:06:03,637 ERROR com.pravinkatiyar.onlinetest.aop.LoggingAspect [http-nio-8110-exec-3] Exception in com.pravinkatiyar.onlinetest.service.impl.UserServiceImpl.createUser() with cause = NULL
2022-01-02 12:06:03,638 ERROR com.pravinkatiyar.onlinetest.aop.LoggingAspect [http-nio-8110-exec-3] Exception in com.pravinkatiyar.onlinetest.controller.UserController.createUser() with cause = NULL
2022-01-02 12:06:03,640 WARN org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver [http-nio-8110-exec-3] Resolved [com.pravinkatiyar.onlinetest.exception.UserAlreadyExistsException: User with username: g4ffh2gf already exists in database!]
2022-01-02 12:06:47,513 DEBUG com.pravinkatiyar.onlinetest.aop.LoggingAspect [http-nio-8110-exec-5] Enter: com.pravinkatiyar.onlinetest.controller.UserController.createUser() with argument[s] = [User [id=, username=g4ffh2gf, password=vghvg, firstName=gvh, lastName=vgvg, gender=, email=gf@gmail.com, phone=9874563210, enabled=true]]
2022-01-02 12:06:47,514 DEBUG com.pravinkatiyar.onlinetest.aop.LoggingAspect [http-nio-8110-exec-5] Enter: com.pravinkatiyar.onlinetest.service.impl.UserServiceImpl.createUser() with argument[s] = [User [id=, username=g4ffh2gf, password=vghvg, firstName=gvh, lastName=vgvg, gender=, email=gf@gmail.com, phone=9874563210, enabled=true], [com.pravinkatiyar.onlinetest.entity.UserRole@1b7a0c3c]]
2022-01-02 12:06:47,518 ERROR com.pravinkatiyar.onlinetest.aop.LoggingAspect [http-nio-8110-exec-5] Exception in com.pravinkatiyar.onlinetest.service.impl.UserServiceImpl.createUser() with cause = NULL
2022-01-02 12:06:47,519 ERROR com.pravinkatiyar.onlinetest.aop.LoggingAspect [http-nio-8110-exec-5] Exception in com.pravinkatiyar.onlinetest.controller.UserController.createUser() with cause = NULL
2022-01-02 12:06:47,520 WARN org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver [http-nio-8110-exec-5] Resolved [com.pravinkatiyar.onlinetest.exception.UserAlreadyExistsException: User with username: g4ffh2gf already exists in database!]
2022-01-02 12:08:27,133 DEBUG com.pravinkatiyar.onlinetest.aop.LoggingAspect [http-nio-8110-exec-7] Enter: com.pravinkatiyar.onlinetest.controller.UserController.createUser() with argument[s] = [User [id=, username=g4ffh2gf, password=gcghchg, firstName=vgvgh, lastName=jvjg, gender=, email=hgyjgf@gmail.com, phone=9632587410, enabled=true]]
2022-01-02 12:08:27,133 DEBUG com.pravinkatiyar.onlinetest.aop.LoggingAspect [http-nio-8110-exec-7] Enter: com.pravinkatiyar.onlinetest.service.impl.UserServiceImpl.createUser() with argument[s] = [User [id=, username=g4ffh2gf, password=gcghchg, firstName=vgvgh, lastName=jvjg, gender=, email=hgyjgf@gmail.com, phone=9632587410, enabled=true], [com.pravinkatiyar.onlinetest.entity.UserRole@6b220550]]
2022-01-02 12:08:27,137 ERROR com.pravinkatiyar.onlinetest.aop.LoggingAspect [http-nio-8110-exec-7] Exception in com.pravinkatiyar.onlinetest.service.impl.UserServiceImpl.createUser() with cause = NULL
2022-01-02 12:08:27,137 ERROR com.pravinkatiyar.onlinetest.aop.LoggingAspect [http-nio-8110-exec-7] Exception in com.pravinkatiyar.onlinetest.controller.UserController.createUser() with cause = NULL
2022-01-02 12:08:27,138 WARN org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver [http-nio-8110-exec-7] Resolved [com.pravinkatiyar.onlinetest.exception.UserAlreadyExistsException: User with username: g4ffh2gf already exists in database!]
2022-01-02 12:14:33,303 DEBUG com.pravinkatiyar.onlinetest.aop.LoggingAspect [http-nio-8110-exec-9] Enter: com.pravinkatiyar.onlinetest.controller.UserController.createUser() with argument[s] = [User [id=, username=g4ffh2gf, password=vhvhj, firstName=hfht, lastName=hjvjh, gender=, email=gfjhfgyj@gmail.com, phone=9632587410, enabled=true]]
2022-01-02 12:14:33,304 DEBUG com.pravinkatiyar.onlinetest.aop.LoggingAspect [http-nio-8110-exec-9] Enter: com.pravinkatiyar.onlinetest.service.impl.UserServiceImpl.createUser() with argument[s] = [User [id=, username=g4ffh2gf, password=vhvhj, firstName=hfht, lastName=hjvjh, gender=, email=gfjhfgyj@gmail.com, phone=9632587410, enabled=true], [com.pravinkatiyar.onlinetest.entity.UserRole@1b8459a0]]
2022-01-02 12:14:33,308 ERROR com.pravinkatiyar.onlinetest.aop.LoggingAspect [http-nio-8110-exec-9] Exception in com.pravinkatiyar.onlinetest.service.impl.UserServiceImpl.createUser() with cause = NULL
2022-01-02 12:14:33,308 ERROR com.pravinkatiyar.onlinetest.aop.LoggingAspect [http-nio-8110-exec-9] Exception in com.pravinkatiyar.onlinetest.controller.UserController.createUser() with cause = NULL
2022-01-02 12:14:33,309 WARN org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver [http-nio-8110-exec-9] Resolved [com.pravinkatiyar.onlinetest.exception.UserAlreadyExistsException: User with username: g4ffh2gf already exists in database!]
2022-01-02 12:16:55,565 INFO com.pravinkatiyar.onlinetest.OnlinetestApplication [restartedMain] Starting OnlinetestApplication using Java 11.0.11 on DESKTOP-TV14ERS with PID 8144 (G:\workspace\onlinetest\target\classes started by Pravin in G:\workspace\onlinetest)
2022-01-02 12:16:55,565 DEBUG com.pravinkatiyar.onlinetest.OnlinetestApplication [restartedMain] Running with Spring Boot v2.5.7, Spring v5.3.13
2022-01-02 12:16:55,565 INFO com.pravinkatiyar.onlinetest.OnlinetestApplication [restartedMain] No active profile set, falling back to default profiles: default
2022-01-02 12:16:56,744 DEBUG com.pravinkatiyar.onlinetest.utils.APIFilter [restartedMain] Filter 'aPIFilter' configured for use
2022-01-02 12:16:59,057 INFO com.pravinkatiyar.onlinetest.OnlinetestApplication [restartedMain] Started OnlinetestApplication in 3.527 seconds (JVM running for 1842.289)
